services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app  # Remove the .:/app line
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      init_db:
        condition: service_completed_successfully

  init_db:
    build: .
    container_name: database
    volumes:
      - sqlite_data:/app  # Remove the .:/app line
    command: >
      bash -c "python create_database.py"
    restart: "no"

volumes:
  sqlite_data: